/* eslint-disable eol-last */
export const SCROLL_TITLE = 'SCROLL_TITLE'
export const CHANG_LOADSTART = 'CHANG_LOADSTART'
export const CHANGE_LOADNEXT = 'CHANGE_LOADNEXT'
export const RECEIVE_NEXTTARTICLES = 'RECEIVE_NEXTTARTICLES'
export const RECEIVE_LATESTARTICLES = 'RECEIVE_LATESTARTICLES'
export const CHANGE_SIDEBAR = 'SIDE_BAR'
export const SIDELIST = 'SIDE_LIST'
export const GET_THEME = 'GET_THEME'
